development:
  adapter: postgresql
  database: agilezen_beta_dev 
  host: localhost
  username: zenzen
  password:
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: agilezen_beta_test
  host: localhost
  username: zenzen
  password:
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: agilezen_beta
  host: localhost
  username: zenzen
  password:
  pool: 5
  timeout: 5000
